# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
linters:
  RuboCop:
    enabled: true
    ignored_cops:
      - Layout/ArgumentAlignment
      - Style/TrailingCommaInArguments
      - Layout/MultilineMethodCallBraceLayout
      - Layout/SpaceInsideHashLiteralBraces
  InlineStyles:
    enabled: false
  LineLength:
    enabled: false
  UnnecessaryStringOutput:
    enabled: false
  ViewLength:
    enabled: false
  ConsecutiveComments:
    enabled: false
