# (The MIT License)
#
# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
linters:
  InlineStyles:
    enabled: false
  LineLength:
    enabled: false
  UnnecessaryStringOutput:
    enabled: false
  ViewLength:
    enabled: false
