AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0
  NewCops: enable
  SuggestExtensions: false
Layout/RescueEnsureAlignment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 25
Style/MultilineTernaryOperator:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 100
Metrics/ClassLength:
  Max: 340
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/ParameterLists:
  Max: 10
Layout/ParameterAlignment:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 25
Layout/LineLength:
  Max: 120
Style/MultilineBlockChain:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
Layout/EmptyLineAfterGuardClause:
  Enabled: false
required:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
