# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/java
readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/mailanes/config.yml
install: |-
  sudo /usr/bin/install-postgres.sh
  pdd -f /dev/null
  bundle install --no-color
  git config --global user.email "server@mailanes.com"
  git config --global user.name "mailanes.com"
release:
  sensitive:
    - config.yml
  script: |-
    bundle exec rake
    rm -rf target
    cp ../config.yml config.yml
    bundle exec rake liquibase
    rm -rf config.yml
merge:
  script: |-
    bundle exec rake
