language: ruby
sudo: required
rvm:
  - 2.6.0
cache: bundler
branches:
  only:
    - master
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
install:
  - travis_retry bundle update
services:
  - postgresql
script:
  - bundle exec rake
after_success:
  - "bash <(curl -s https://codecov.io/bash)"

