language: ruby
rvm:
  - 2.6.0
cache: bundler
branches:
  only:
    - master
services:
  - postgresql
install:
  - travis_retry bundle update
script:
  - rake
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
